### ISSUE TITLE
Accessing this from external IP?

### ISSUE THREAD

**Issue by morriscode** [certego/pcapoptikon#1]
I'm not able to access this outside of the host itself, is there a seperate run command required to expose this to the internet via the host?

**Comment by pdelsante** [comment]
Hello,

What command are you using to start the container?

In theory, when using `-p=8000:8000` to expose the container's port to the host, that port will be open to the outside network as well, see here for more info: https://docs.docker.com/engine/userguide/networking/default_network/binding/

Are you sure you don't have anything that may be blocking connections on the host? For example `ufw`, `shorewall` or any custom iptables rules that may interfere with the ones that docker adds to `iptables` itself?

I am assuming you are using Linux or Mac: things are pretty different if you're using Windows, because on Windows docker runs in a virtual machine so you'll need the virtual machine's IP address to be able to connect to the service (by default, it's `192.168.99.100`).

**Comment by morriscode** [comment]
Thanks! I'm using ubuntu server 14.04 LTS. This is a fresh install of ubuntu server. I've reloaded the server a few times thinking it was perhaps something I'd done prior to installing. This instance is a fresh image, apt-get update/upgrade and docker install. 

The command I'm using to start it is 
`sudo docker run -d --name=pcapoptikon --volumes-from=pcapoptikon_data -v=/var/log/pcapoptikon:/var/log -v=/var/tmp/pcapoptikon:/var/tmp -p=8000:8000 pdelsante/pcapoptikon`

Netstat -l shows 

> Proto Recv-Q Send-Q Local Address           Foreign Address         State
> tcp        0      0 _:7070                  *:_                     LISTEN
> tcp        0      0 localhost:27017         _:_                     LISTEN
> tcp        0      0 localhost:mysql         _:_                     LISTEN
> tcp        0      0 localhost:28017         _:_                     LISTEN
> tcp6       0      0 [::]:7070               [::]:\*                  LISTEN
> tcp6       0      0 [::]:8000               [::]:\*                  LISTEN

Just for fun, I was able to get your rumal front end working, but that's not a docker container. Not sure why I can't reach this.

**Comment by morriscode** [comment]
Nmap scan doesn't see the port either but it does see other ports open. Namely the one I use to SSH in on. It's like the docker container is not forwarding the port to the host.

**Comment by pdelsante** [comment]
What's the result of these two commands?

``` sh
$ ufw status
$ iptables -L
```

If you have UFW enabled, it may have interfered with Docker's iptables rules. I can't think of any other thing that may be preventing you from reaching port 8000 from the outside, since it's listening on `[::]:8000` which is an IPv6 address but is mapped to both IPv4 and IPv6, and should allow connections from any interface/address.

**Comment by morriscode** [comment]
Thank you!

```
sudo ufw status
Status: inactive
```

```
target     prot opt source               destination
fail2ban-ssh  tcp  --  anywhere             anywhere             multiport dports ssh

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-ISOLATION  all  --  anywhere             anywhere
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

Chain fail2ban-ssh (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere

```

**Comment by morriscode** [comment]
morriscode@vps1:~$ nmap xx.xx.xxx.xx -p 7000-9000

Starting Nmap 6.40 ( http://nmap.org ) at 2016-06-02 17:13 EDT
Nmap scan report for redacted
Host is up (0.00063s latency).
Not shown: 2000 closed ports
PORT     STATE SERVICE
22/tcp open  ssh

**Comment by pdelsante** [comment]
There should be an explicit rule forwarding traffic from `localhost:8000` to `docker-container:8000` but I don't see any. Let's look at the IPv6 rules with:

```
$ ip6tables -L
```

Also, are you using docker from the default ubuntu repo, or did you install it from docker's own repo? I would highly recommend the latter.

**Comment by pdelsante** [comment]
Maybe it's a dumb question but I see you are talking about a VPS. Are you sure that there isn't any firewall on the VPS server? For example, Amazon AWS does have a default firewall configuration that only lets you reach port 22/tcp by default and you have to open up any other ports by hand.

**Comment by morriscode** [comment]
Definitely not a dumb question. This particular host doesn't have any restrictions on ports, I have another VPS with them, but for fun I started a netcat listener on port 8000 and it was accessible. 

I installed docker from dockers repo, not the ubuntu repo. I followed these instructions: https://docs.docker.com/engine/installation/linux/ubuntulinux/

```
sudo ip6tables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         


Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination   
```

**Comment by morriscode** [comment]
I'll reload the VPS and give it a go again.

**Comment by pdelsante** [comment]
This is my iptables output with a couple of running containers exposing ports 8000 and 8080:

```
$ sudo iptables -L                       
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         
DOCKER-ISOLATION  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere            

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain DOCKER (1 references)
target     prot opt source               destination         
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:8000
ACCEPT     tcp  --  anywhere             172.17.0.3           tcp dpt:http-alt

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination         
RETURN     all  --  anywhere             anywhere
```

I think you were missing entries in the `DOCKER` chain, but unfortunately I have no idea why...

**Comment by morriscode** [comment]
I've tried several times. Currently I see the docker chain in Iptables now but it's still inaccessible

morriscode@ubuntu:~$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.1           tcp dpt:8000

**Comment by morriscode** [comment]
I can ping the container also, it's almost like the script isn't running at all. Is there a way to get a shell on it?

**Comment by morriscode** [comment]
Looking at the container it appears to have several errors that may indicate why the webserver isn't responding.

Updating sid-msg.map
Starting Suricata...
Starting the PCAPOptikon HTTP Server...
**/opt/pcapoptikon/start.sh: line 61: /var/log/suricata/suricata.log: No such file or directory**
Starting the PCAPOptikon worker daemon...
Running on: http://172.17.0.3:8000/
Username: admin
**ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)**
Api-Key:

**Comment by morriscode** [comment]
Adding a Shell to the container and looking at it, the SQL service never starts.

root@af5cbb9fd875:/# service mysql status
- MySQL is stopped.
  root@af5cbb9fd875:/# service mysql start
- Starting MySQL database server mysqld
  ...fail!

**Comment by morriscode** [comment]
I went to check /var/log/mysql/error.log to see why it wasn't starting... well there was no /var/log/mysql folder. I figured the apt-get install would've handled that, but alas. Once I built the folder, I was able to run the start script without errors.

**Comment by morriscode** [comment]
So every pcap I submitted said failed. Apparently you have unified 2 alert disabled in suricata.yaml
- unified2-alert:
    enabled: no

**Comment by pdelsante** [comment]
Hello,

You are right about the `/var/log/mysql` folder, and the same applies to `/var/log/suricata`, I already fixed both of them.

You are also right about `unified2-alert` being disabled by default, this probably changed in Suricata 3. I'll fix that tomorrow, now I definitely need some sleep :-)

Thanks a lot for taking your time to debug and report this!!!

**Comment by morriscode** [comment]
Happy to help! I didn't want to step on any toes. I think I have it all
working all of my pcaps show 0/0 matches though. I know snort will fire on
these same pcaps with the free emerging threats rulesets so I'd assume
suricata should also since they're true positives.

**Comment by pdelsante** [comment]
Are you sure that oinkmaster is actually downloading the rules for you? Please have a look at `/var/log/pcapoptikon_startup.log` in the container, which should be `/var/log/pcapoptikon/pcapoptikon_startup.log` in your host.

You should see something like this:

```
Using default ET Open ruleset (to change this, please pass your ETPro oinkcode as the first param to /opt/pcapoptikon/start.sh
Running OinkMaster to update signatures...
Loading /etc/oinkmaster.conf
Downloading file from http://rules.emergingthreats.net/open/suricata/emerging.rules.tar.gz... done.
Archive successfully downloaded, unpacking... done.
Setting up rules structures... done.
Processing downloaded rules... disablesid 0, enablesid 0, modifysid 0, localsid 0, total rules 22972
Setting up rules structures... done.
Comparing new files to the old ones... done.
Checking flowbits dependencies... problems found:

WARNING: SID 2017126 depends on flowbit "FlimKit.SWF.Redirect" which is set in INACTIVE SID 2017125 (SID 2017126 is broken unless you also enable SID 2017125).
Updating local rules files... done.

[***] Results from Oinkmaster started 20160607 22:11:07 [***]

[*] Rules modifications: [*]
    None.

[---]     Removed non-rule lines:    [---]

     -> Removed from sid-msg.map (21):
        2240001 || SURICATA DNS Unsollicited response
        2240002 || SURICATA DNS malformed request data
        2240003 || SURICATA DNS malformed response data
        2240004 || SURICATA DNS Not a request
        2240005 || SURICATA DNS Not a response
        2240006 || SURICATA DNS Z flag set
        2240007 || SURICATA DNS request flood detected
        2240008 || SURICATA DNS flow memcap reached
        2250001 || SURICATA Modbus invalid Protocol version
        2250002 || SURICATA Modbus unsolicited response
        2250003 || SURICATA Modbus invalid Length
        2250004 || SURICATA Modbus invalid Unit Identifier
        2250005 || SURICATA Modbus invalid Function code
        2250006 || SURICATA Modbus invalid Value
        2250007 || SURICATA Modbus Exception code invalid
        2250008 || SURICATA Modbus Data mismatch
        2250009 || SURICATA Modbus Request flood detected
        2260000 || SURICATA Applayer Mismatch protocol both directions
        2260001 || SURICATA Applayer Wrong direction first Data
        2260002 || SURICATA Applayer Detect protocol only one direction
        2260003 || SURICATA Applayer Protocol detection skipped

[*] Added files: [*]
    None.
```

**Comment by morriscode** [comment]
Yup it's definitely downloading rulesets.

**Comment by pdelsante** [comment]
Then it should definitely work as expected. Could you please try and pull the latest docker image from dockerhub and try it out?

```
$ docker pull pdelsante/pcapoptikon
```

**Comment by morriscode** [comment]
Yes that is
